# These are supported funding model platforms

# GitHub Sponsors
# github: [OneStepAt4time]  # Uncomment and add your username when you set up GitHub Sponsors

# Buy Me a Coffee
custom: ['https://buymeacoffee.com/onestepat4time']
